/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/schema.json
export type PostReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "post";
};

export type BlogPage = {
  _id: string;
  _type: "blogPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  metadata?: Metadata;
  heroTitle: string;
  featuredPost?: PostReference;
  listTitle: string;
};

export type Metadata = {
  _type: "metadata";
  metaTitle?: string;
  metaDescription?: string;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  metadata?: Metadata;
};

export type Layout = {
  _id: string;
  _type: "layout";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  navLinks?: Array<
    {
      _key: string;
    } & Link
  >;
  navCtas?: Array<
    {
      _key: string;
    } & Button
  >;
  footerColumns?: Array<
    {
      _key: string;
    } & FooterColumn
  >;
  copyrightText?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  picture: ImageWithAlt;
  socialUrl: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ImageWithAlt = {
  _type: "imageWithAlt";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt: string;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  excerpt: string;
  intro?: SimplePortableText;
  featuredImage?: ImageWithAlt;
  body: PortableText;
  date: string;
  authors: Array<
    {
      _key: string;
    } & AuthorReference
  >;
  categories: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  relatedPosts?: Array<
    {
      _key: string;
    } & PostReference
  >;
};

export type PortableText = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href: string;
        openInNewTab?: boolean;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | ({
      _key: string;
    } & Quote)
  | ({
      _key: string;
    } & ImageWithAlt)
  | ({
      _key: string;
    } & Code)
>;

export type SimplePortableText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal";
  listItem?: never;
  markDefs?: Array<{
    href: string;
    openInNewTab?: boolean;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type Quote = {
  _type: "quote";
  text: string;
  attributionName?: string;
  attributionRole?: string;
};

export type FooterColumn = {
  _type: "footerColumn";
  title: string;
  links?: Array<
    {
      _key: string;
    } & Link
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Button = {
  _type: "button";
  label: string;
  href: string;
  openInNewTab?: boolean;
  variant: "dark" | "light";
};

export type Link = {
  _type: "link";
  label: string;
  href: string;
  openInNewTab?: boolean;
};

export type Code = {
  _type: "code";
  language?: string;
  filename?: string;
  code?: string;
  highlightedLines?: Array<number>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | PostReference
  | BlogPage
  | Metadata
  | HomePage
  | Layout
  | Category
  | Slug
  | Author
  | SanityImageAssetReference
  | ImageWithAlt
  | AuthorReference
  | CategoryReference
  | Post
  | PortableText
  | SimplePortableText
  | Quote
  | FooterColumn
  | SanityImageCrop
  | SanityImageHotspot
  | Button
  | Link
  | Code
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: LAYOUT_QUERY
// Query: *[_type == "layout"][0] {    navLinks[] { _key, label, href, openInNewTab },    navCtas[] { _key, label, href, openInNewTab, variant },    footerColumns[] { _key, title, links[] { _key, label, href, openInNewTab } },    copyrightText  }
export type LAYOUT_QUERY_RESULT = {
  navLinks: Array<{
    _key: string;
    label: string;
    href: string;
    openInNewTab: boolean | null;
  }> | null;
  navCtas: Array<{
    _key: string;
    label: string;
    href: string;
    openInNewTab: boolean | null;
    variant: "dark" | "light";
  }> | null;
  footerColumns: Array<{
    _key: string;
    title: string;
    links: Array<{
      _key: string;
      label: string;
      href: string;
      openInNewTab: boolean | null;
    }> | null;
  }> | null;
  copyrightText: string | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_type == "homePage"][0] { metadata }
export type HOME_PAGE_QUERY_RESULT = {
  metadata: Metadata | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: BLOG_PAGE_QUERY
// Query: *[_type == "blogPage"][0] {    metadata,    heroTitle,    listTitle,    "featuredPost": coalesce(      featuredPost-> {   _id,  title,  "slug": slug.current,  excerpt,  date,  featuredImage {   asset,  hotspot,  crop,  "alt": coalesce(alt, asset->altText) },  categories[]-> { _id, title, "slug": slug.current } },      *[_type == "post" && defined(slug.current)] | order(date desc, _createdAt desc)[0] {   _id,  title,  "slug": slug.current,  excerpt,  date,  featuredImage {   asset,  hotspot,  crop,  "alt": coalesce(alt, asset->altText) },  categories[]-> { _id, title, "slug": slug.current } }    )  }
export type BLOG_PAGE_QUERY_RESULT = {
  metadata: Metadata | null;
  heroTitle: string;
  listTitle: string;
  featuredPost: {
    _id: string;
    title: string;
    slug: string;
    excerpt: string;
    date: string;
    featuredImage: {
      asset: SanityImageAssetReference | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      alt: string;
    } | null;
    categories: Array<{
      _id: string;
      title: string;
      slug: string;
    }>;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: CATEGORIES_QUERY
// Query: *[_type == "category" && defined(slug.current)] | order(title asc) { _id, title, "slug": slug.current }
export type CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: POSTS_QUERY
// Query: *[    _type == "post"    && defined(slug.current)    && _id != $exclude    && ($category == null || $category in categories[]->slug.current)  ] | order(date desc, _createdAt desc) [$offset...$end] {   _id,  title,  "slug": slug.current,  excerpt,  date,  featuredImage {   asset,  hotspot,  crop,  "alt": coalesce(alt, asset->altText) },  categories[]-> { _id, title, "slug": slug.current } }
export type POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  excerpt: string;
  date: string;
  featuredImage: {
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string;
  } | null;
  categories: Array<{
    _id: string;
    title: string;
    slug: string;
  }>;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: POSTS_COUNT_QUERY
// Query: count(*[    _type == "post"    && defined(slug.current)    && _id != $exclude    && ($category == null || $category in categories[]->slug.current)  ])
export type POSTS_COUNT_QUERY_RESULT = number;

// Source: src/sanity/lib/queries.ts
// Variable: POST_SLUGS_QUERY
// Query: *[_type == "post" && defined(slug.current)] { "slug": slug.current }
export type POST_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: POST_QUERY
// Query: *[_type == "post" && slug.current == $slug][0] {      _id,  title,  "slug": slug.current,  excerpt,  date,  featuredImage {   asset,  hotspot,  crop,  "alt": coalesce(alt, asset->altText) },  categories[]-> { _id, title, "slug": slug.current },    intro[] {   ...,  _type == "imageWithAlt" => {   asset,  hotspot,  crop,  "alt": coalesce(alt, asset->altText) },  markDefs[] { ... } },    body[] {   ...,  _type == "imageWithAlt" => {   asset,  hotspot,  crop,  "alt": coalesce(alt, asset->altText) },  markDefs[] { ... } },    authors[]-> {   _id,  name,  socialUrl,  picture {   asset,  hotspot,  crop,  "alt": coalesce(alt, asset->altText) } },    "relatedPosts": select(      count(relatedPosts) > 0 => relatedPosts[]-> {   _id,  title,  "slug": slug.current,  excerpt,  date,  featuredImage {   asset,  hotspot,  crop,  "alt": coalesce(alt, asset->altText) },  categories[]-> { _id, title, "slug": slug.current } },      *[        _type == "post"        && _id != ^._id        && defined(slug.current)        && count(categories[@._ref in ^.^.categories[]._ref]) > 0      ] | order(date desc, _createdAt desc)[0...3] {   _id,  title,  "slug": slug.current,  excerpt,  date,  featuredImage {   asset,  hotspot,  crop,  "alt": coalesce(alt, asset->altText) },  categories[]-> { _id, title, "slug": slug.current } }    ),    "previous": *[_type == "post" && defined(slug.current) && date < ^.date] | order(date desc)[0] { title, "slug": slug.current },    "next": *[_type == "post" && defined(slug.current) && date > ^.date] | order(date asc)[0] { title, "slug": slug.current }  }
export type POST_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  excerpt: string;
  date: string;
  featuredImage: {
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string;
  } | null;
  categories: Array<{
    _id: string;
    title: string;
    slug: string;
  }>;
  intro: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs: Array<{
      href: string;
      openInNewTab?: boolean;
      _type: "link";
      _key: string;
    }> | null;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs: Array<{
          href: string;
          openInNewTab?: boolean;
          _type: "link";
          _key: string;
        }> | null;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        _key: string;
        _type: "code";
        language?: string;
        filename?: string;
        code?: string;
        highlightedLines?: Array<number>;
        markDefs: null;
      }
    | {
        _key: string;
        _type: "imageWithAlt";
        asset: SanityImageAssetReference | null;
        media?: unknown;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
        alt: string;
        markDefs: null;
      }
    | {
        _key: string;
        _type: "quote";
        text: string;
        attributionName?: string;
        attributionRole?: string;
        markDefs: null;
      }
  >;
  authors: Array<{
    _id: string;
    name: string;
    socialUrl: string;
    picture: {
      asset: SanityImageAssetReference | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      alt: string;
    };
  }>;
  relatedPosts: Array<{
    _id: string;
    title: string;
    slug: string;
    excerpt: string;
    date: string;
    featuredImage: {
      asset: SanityImageAssetReference | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      alt: string;
    } | null;
    categories: Array<{
      _id: string;
      title: string;
      slug: string;
    }>;
  }> | null;
  previous: {
    title: string;
    slug: string;
  } | null;
  next: {
    title: string;
    slug: string;
  } | null;
} | null;

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_type == "layout"][0] {\n    navLinks[] { _key, label, href, openInNewTab },\n    navCtas[] { _key, label, href, openInNewTab, variant },\n    footerColumns[] { _key, title, links[] { _key, label, href, openInNewTab } },\n    copyrightText\n  }\n': LAYOUT_QUERY_RESULT;
    '\n  *[_type == "homePage"][0] { metadata }\n': HOME_PAGE_QUERY_RESULT;
    '\n  *[_type == "blogPage"][0] {\n    metadata,\n    heroTitle,\n    listTitle,\n    "featuredPost": coalesce(\n      featuredPost-> { \n  _id,\n  title,\n  "slug": slug.current,\n  excerpt,\n  date,\n  featuredImage { \n  asset,\n  hotspot,\n  crop,\n  "alt": coalesce(alt, asset->altText)\n },\n  categories[]-> { _id, title, "slug": slug.current }\n },\n      *[_type == "post" && defined(slug.current)] | order(date desc, _createdAt desc)[0] { \n  _id,\n  title,\n  "slug": slug.current,\n  excerpt,\n  date,\n  featuredImage { \n  asset,\n  hotspot,\n  crop,\n  "alt": coalesce(alt, asset->altText)\n },\n  categories[]-> { _id, title, "slug": slug.current }\n }\n    )\n  }\n': BLOG_PAGE_QUERY_RESULT;
    '\n  *[_type == "category" && defined(slug.current)] | order(title asc) { _id, title, "slug": slug.current }\n': CATEGORIES_QUERY_RESULT;
    '\n  *[\n    _type == "post"\n    && defined(slug.current)\n    && _id != $exclude\n    && ($category == null || $category in categories[]->slug.current)\n  ] | order(date desc, _createdAt desc) [$offset...$end] { \n  _id,\n  title,\n  "slug": slug.current,\n  excerpt,\n  date,\n  featuredImage { \n  asset,\n  hotspot,\n  crop,\n  "alt": coalesce(alt, asset->altText)\n },\n  categories[]-> { _id, title, "slug": slug.current }\n }\n': POSTS_QUERY_RESULT;
    '\n  count(*[\n    _type == "post"\n    && defined(slug.current)\n    && _id != $exclude\n    && ($category == null || $category in categories[]->slug.current)\n  ])\n': POSTS_COUNT_QUERY_RESULT;
    '\n  *[_type == "post" && defined(slug.current)] { "slug": slug.current }\n': POST_SLUGS_QUERY_RESULT;
    '\n  *[_type == "post" && slug.current == $slug][0] {\n    \n  _id,\n  title,\n  "slug": slug.current,\n  excerpt,\n  date,\n  featuredImage { \n  asset,\n  hotspot,\n  crop,\n  "alt": coalesce(alt, asset->altText)\n },\n  categories[]-> { _id, title, "slug": slug.current }\n,\n    intro[] { \n  ...,\n  _type == "imageWithAlt" => { \n  asset,\n  hotspot,\n  crop,\n  "alt": coalesce(alt, asset->altText)\n },\n  markDefs[] { ... }\n },\n    body[] { \n  ...,\n  _type == "imageWithAlt" => { \n  asset,\n  hotspot,\n  crop,\n  "alt": coalesce(alt, asset->altText)\n },\n  markDefs[] { ... }\n },\n    authors[]-> { \n  _id,\n  name,\n  socialUrl,\n  picture { \n  asset,\n  hotspot,\n  crop,\n  "alt": coalesce(alt, asset->altText)\n }\n },\n    "relatedPosts": select(\n      count(relatedPosts) > 0 => relatedPosts[]-> { \n  _id,\n  title,\n  "slug": slug.current,\n  excerpt,\n  date,\n  featuredImage { \n  asset,\n  hotspot,\n  crop,\n  "alt": coalesce(alt, asset->altText)\n },\n  categories[]-> { _id, title, "slug": slug.current }\n },\n      *[\n        _type == "post"\n        && _id != ^._id\n        && defined(slug.current)\n        && count(categories[@._ref in ^.^.categories[]._ref]) > 0\n      ] | order(date desc, _createdAt desc)[0...3] { \n  _id,\n  title,\n  "slug": slug.current,\n  excerpt,\n  date,\n  featuredImage { \n  asset,\n  hotspot,\n  crop,\n  "alt": coalesce(alt, asset->altText)\n },\n  categories[]-> { _id, title, "slug": slug.current }\n }\n    ),\n    "previous": *[_type == "post" && defined(slug.current) && date < ^.date] | order(date desc)[0] { title, "slug": slug.current },\n    "next": *[_type == "post" && defined(slug.current) && date > ^.date] | order(date asc)[0] { title, "slug": slug.current }\n  }\n': POST_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
