import { markdownForPath, notFoundMarkdown } from "@/modules/markdown-content";
import { sanityFetch } from "@/modules/sanity/lib/live";
import { POST_SLUGS_QUERY } from "@/modules/sanity/lib/queries";

/**
 * Markdown representation of any page. Reached through the rewrites in `next.config.ts` when a
 * client prefers `text/markdown` (or requests the `.md` sibling of a page URL).
 *
 * Prerendered like the HTML pages: every known page at build time, anything else on first request,
 * and regenerated by the same tag-based revalidation the pages use.
 */

const HEADERS = {
  "Content-Type": "text/markdown; charset=utf-8",
  // The page URL has two representations, so shared caches must key on `Accept`.
  Vary: "Accept",
} as const;

export const dynamicParams = true;

export async function generateStaticParams() {
  const { data } = await sanityFetch({
    query: POST_SLUGS_QUERY,
    perspective: "published",
    stega: false,
  });

  return [{ path: [] }, { path: ["blog"] }, ...data.map(({ slug }) => ({ path: ["blog", slug] }))];
}

export async function GET(
  _request: Request,
  { params }: RouteContext<"/api/markdown/[[...path]]">,
) {
  const { path = [] } = await params;
  const pathname = `/${path.map(decodeURIComponent).join("/")}`;

  const markdown = await markdownForPath(pathname);
  if (markdown === null) {
    return new Response(notFoundMarkdown(pathname), { status: 404, headers: HEADERS });
  }

  return new Response(markdown, { headers: HEADERS });
}
